### ISSUE TITLE
Playlist-remove is not working due to Plex API change

### ISSUE THREAD

**Issue by ozdek** [Monschichi/plex_downloader#78]
--playlist-remove     cleanup playlist after downloading

/usr/local/bin/downloader:261: DeprecationWarning: Call to deprecated function or method "removeItem", use "removeItems" instead.                                                                                     
  pd.process_playlist(playlist=pl, remove=args.playlist_remove)                                                                                                                                                  | 0/1
WARNING:plexapi:Call to deprecated function or method "removeItem", use "removeItems" instead.
video count:   0%|                                                                                                                                                                                               | 0/1
Traceback (most recent call last):
  File "/usr/local/bin/downloader", line 261, in <module>
    pd.process_playlist(playlist=pl, remove=args.playlist_remove)
  File "/usr/local/bin/downloader", line 56, in process_playlist
    playlist.removeItem(video)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/plexapi/utils.py", line 506, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/plexapi/playlist.py", line 215, in removeItem
    self.removeItems(item)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/plexapi/playlist.py", line 237, in removeItems
    self._server.query(key, method=self._server._session.delete)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/plexapi/server.py", line 667, in query
    raise NotFound(message)
plexapi.exceptions.NotFound: (404) not_found; https://*****.plex.direct:42518/playlists/699952/items/None <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>

**Comment by Monschichi** [comment]
Thanks for the report :+1:, I've updated the code to use `removeItems` now.
