### ISSUE TITLE
Can't start app

### ISSUE THREAD

**Issue by julio8a** [Monschichi/plex_downloader#80]
sorry total noob, I'm getting this message:
```
Traceback (most recent call last):
  File "./downloader.py", line 198, in <module>
    authentication = netrc.netrc().authenticators('plex')
  File "/usr/lib/python3.8/netrc.py", line 30, in __init__
    self._parse(file, fp, default_netrc)
  File "/usr/lib/python3.8/netrc.py", line 104, in _parse
    raise NetrcParseError(
netrc.NetrcParseError: ~/.netrc access too permissive: access permissions must restrict access to only the owner (/root/.netrc, line 3)
```

I'm sure it has to do with how and where I'm setting up the `.netrc` file?

any help or direction would be appreciated

**Comment by julio8a** [comment]
fixed it. I had to create a user and place the file in the `/home/user` directory.
